import "./holamundo.js";
import "./src/Tokens/Token.js";
import "./src/Login/Login.js";
import "./src/Registro/RegistroUsuario.js";
import "./src/Disponibilidad Citas datos usuario/DatosUsuario.js";
import "./src/Disponibilidad Citas datos usuario/mostrarCitas.js";
import "./src/Disponibilidad Citas datos usuario/ServiciosDisponibles.js";
import "./src/agenda/AgendarCita.js";
import "./src/Validaciones/ValidarHoras.js";
import "./src/Disponibilidad Citas datos usuario/RecodrdatoriosCitas.js";
import "./src/Reservas/Reservas.js";
import "./src/Reservas/CancelarReservas.js";
import "./src/Tokens/LimpiezaTokens.js";
import "./src/Disponibilidad Citas datos usuario/confirmarcitas.js";
import "./src/Disponibilidad Citas datos usuario/CancelarCita.js";
import "./src/sliderBar/NombreUser.js";
import "./src/RegistroNegocio/RegistroNegocio.js";
import "./src/Ajustes/Ajustes.js";
import "./src/Cerrar sesion/CerrarSesion.js";
import "./src/Restablecimientos/Restablecercontraseña.js";
import "./src/Disponibilidad Citas datos usuario/FechasEspeciales.js";
import "./src/VincularWhatsApp/VincularWpp.js";
import "./src/VincularWhatsApp/EnvioMsjWpp.js";
import "./src/Disponibilidad Citas datos usuario/ActualizarCita.js";
import "./src/Ajustes/AjustesCapacidadDia.js";
import "./src/TuPagina/identidad.js";
import "./src/TuPagina/guardarIdentidad.js";
import "./src/ServiciosCatalogo/GuardarCatalogo.js";
import "./src/ServiciosCatalogo/ObtenerCatalogo.js";
import "./src/ServiciosCatalogo/EliminarCatalogo.js";
import "./src/ServiciosCatalogo/ValidarCantidadCitas.js";
//const RutaFront = "https://fromprueba-production.up.railway.app";// cmabiar por el dominio del front 

